//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap apple {
            get {
                object obj = ResourceManager.GetObject("apple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap banana {
            get {
                object obj = ResourceManager.GetObject("banana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap grape {
            get {
                object obj = ResourceManager.GetObject("grape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pear {
            get {
                object obj = ResourceManager.GetObject("pear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///  &lt;title&gt;socket图片推流演示&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;h1&gt;socket图片推流演示&lt;/h1&gt;
        ///  &lt;div&gt;
        ///    &lt;input type=&quot;text&quot; id=&quot;address&quot; value=&quot;127.0.0.1:8082&quot;&gt;
        ///    &lt;button id=&quot;connect&quot;&gt;连接&lt;/button&gt;
        ///    &lt;span&gt;8082&lt;/span&gt;
        ///  &lt;/div&gt;
        ///  &lt;img id=&quot;img&quot; /&gt;
        ///  &lt;script&gt;
        ///    const addressText = document.getElementById(&apos;addr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string socket {
            get {
                return ResourceManager.GetString("socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap tangerine {
            get {
                object obj = ResourceManager.GetObject("tangerine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap watermelon {
            get {
                object obj = ResourceManager.GetObject("watermelon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///  &lt;title&gt;webSocket演示&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;h1&gt;webSocket演示&lt;/h1&gt;
        ///  &lt;div&gt;
        ///    &lt;input type=&quot;text&quot; id=&quot;address&quot; value=&quot;127.0.0.1:8083&quot;&gt;
        ///    &lt;button id=&quot;connect&quot;&gt;连接&lt;/button&gt;
        ///    &lt;span&gt;8083 8084&lt;/span&gt;
        ///  &lt;/div&gt;
        ///  &lt;div&gt;
        ///    &lt;input type=&quot;text&quot; id=&quot;msg&quot; disabled&gt;
        ///    &lt;button id=&quot;send&quot; disabled [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string webSocket {
            get {
                return ResourceManager.GetString("webSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///  &lt;title&gt;webSocket图片推流演示&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;h1&gt;webSocket图片推流演示&lt;/h1&gt;
        ///  &lt;div&gt;
        ///    &lt;input type=&quot;text&quot; id=&quot;address&quot; value=&quot;127.0.0.1:8083&quot;&gt;
        ///    &lt;button id=&quot;connect&quot;&gt;连接&lt;/button&gt;
        ///    &lt;span&gt;8083 8084&lt;/span&gt;
        ///  &lt;/div&gt;
        ///  &lt;img id=&quot;img&quot; /&gt;
        ///  &lt;script&gt;
        ///    const addressText = document.getElemen [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string webSocket2 {
            get {
                return ResourceManager.GetString("webSocket2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;zh-cmn-Hans&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///  &lt;title&gt;webSocket图片推流演示2&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;h1&gt;webSocket图片推流演示2&lt;/h1&gt;
        ///  &lt;div&gt;
        ///    &lt;input type=&quot;text&quot; id=&quot;address&quot; value=&quot;127.0.0.1:8085&quot;&gt;
        ///    &lt;button id=&quot;connect&quot;&gt;连接&lt;/button&gt;
        ///    &lt;span&gt;8085&lt;/span&gt;
        ///  &lt;/div&gt;
        ///  &lt;img id=&quot;img&quot; /&gt;
        ///  &lt;span id=&quot;fps&quot; style=&quot;position:absolute;top:10px;right: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string webSocket3 {
            get {
                return ResourceManager.GetString("webSocket3", resourceCulture);
            }
        }
    }
}
